name: Update Star Feed

on:
  schedule:
    - cron: '0 */8 * * *'  # Runs every 8 hours. Adjust this as needed.
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        bucket: ['high', 'medium', 'low']

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Star Feed
      run: |
        chmod +x update_star_feed.sh
        ./update_star_feed.sh ${{ secrets.GH_TOKEN }} ${{ matrix.bucket }} ${{ secrets.GITHUB_TOKEN }}

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add -A
        git commit -m "Updated star feed for ${{ matrix.bucket }} bucket"
        git push
